### ISSUE TITLE
Preserve attributes in fct_drop?

### ISSUE THREAD

**Issue by dpavlic** [tidyverse/forcats#83]
One of the ways in which fct_drop is very much the same as droplevels is that it removes attributes (such as Hmisc labels) when it drops extra factor levels:

```
library(Hmisc)
library(forcats)

a <- data.frame(a = factor(c('a', 'b', 'c')), b = c(1:3))
a <- a[1:2, ]
label(a$a) <- 'Var a'
a$a_drop <- fct_drop(a$a)
```

They are there in the original:

```
> attributes(a$a)
$levels
[1] "a" "b" "c"

$class
[1] "labelled" "factor"  

$label
[1] "Var a"
```

Gone in the drop:

```
> attributes(a$a_drop)
$levels
[1] "a" "b"

$class
[1] "factor"
```

Would it be possible to preserve them?

**Comment by hadley** [comment]
I can't see any easy way to make this happen without a bunch of work unfortunately. `fct_drop()` has to create a new factor, and there's no obviously way to make this generic.

**Comment by hadley** [comment]
Hmmm, maybe this is the point of the `refactor()` function

**Comment by hadley** [comment]
Fixed in 090160d108ce589eabf86a4cda50e09a85b80552

**Comment by tjtnew** [comment]
I think this is still an issue as `refactor` overwrites the class with the reset result of `factor`:  
https://github.com/tidyverse/forcats/blob/fb11604d2e67f9ef325b1bebded93244dedcfb15/R/lvls.R#L92-L100 I think this can be fixed by adding `class(new_f) <- NULL` in between lines 97 and 98.  Happy to do a pull request if appropriate.  

Example of current behaviour below
``` r
library(forcats, quietly = TRUE)
library(Hmisc, quietly = TRUE)

a <- data.frame(a = factor(c('a', 'b', 'c')), b = c(1:3))
a <- a[1:2, ]
label(a$a) <- 'Var a'
a$a_drop <- fct_drop(a$a)

# original attributes
attributes(a$a)
#> $levels
#> [1] "a" "b" "c"
#> 
#> $class
#> [1] "labelled" "factor"  
#> 
#> $label
#> [1] "Var a"

# new attributes - labelled class dropped
attributes(a$a_drop)
#> $levels
#> [1] "a" "b"
#> 
#> $class
#> [1] "factor"
#> 
#> $label
#> [1] "Var a"
```

**Comment by khusmann** [comment]
@TimTaylor I've run into this issue as well, and in addition to `fct_drop()` it affects a bunch of methods downstream of `refactor()` like `lvls_expand()`, `lvls_reorder()`, `fct_lump_n()`, etc.

I don't think it's as simple as `class(new_f) <- NULL`, because `refactor()` also sometimes need to set or unset `ordered` in the class attribute. This is relatively simple to remedy though; I have a PR I'll submit in a bit.
